name: dotfiles CI

on:
  pull_request:
    branches: [master]
  push:

jobs:
  check_init:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup
        run: sh ./init.sh
  approve:
    runs-on: macos-latest
    needs: "check_init"
    steps:
      - uses: actions/checkout@v2
      - name: approve
        run: gh pr review ${{ github.event.number }} --comment --body "SetUp Home Brew Pass 🙌"
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  automerge:
    runs-on: ubuntu-latest
    needs: "approve"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: automerge
        run: gh pr merge ${{ github.event.number }} -s
