name: CI for master branch

on:
  push:
    branches: [master]

jobs:
  itest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: itest
        run: curl -fsSL https://raw.githubusercontent.com/fumiya-kume/dotfiles/master/init.sh | bash